api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: true
      targetPort: 8080
      transport: http
      allowInsecure: false
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: keycloak-admin-password
        value: '{{ securedParameter "keycloak_password" }}'
  template:
    volumes:
      - name: keycloak-faugdemoapphost32c5b5b8c5keycloakdata
        storageType: AzureFile
        storageName: {{ .Env.SERVICE_KEYCLOAK_VOLUME_FAUGDEMOAPPHOST32C5B5B8C5KEYCLOAKDATA_NAME }} 
    containers:
      - image: {{ .Image }}
        name: keycloak
        args:
          - start
          - --import-realm
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: KEYCLOAK_ADMIN
            value: '{{ parameter "keycloak_username" }}'
          - name: KEYCLOAK_ADMIN_PASSWORD
            secretRef: keycloak-admin-password
        volumeMounts:
          - volumeName: keycloak-faugdemoapphost32c5b5b8c5keycloakdata
            mountPath: /opt/keycloak/data
    scale:
      minReplicas: 1
tags:
  azd-service-name: keycloak
  aspire-resource-name: keycloak
